In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/jan_2018.csv",index_col=0)
df2 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/feb_2018.csv",index_col=0)
df3 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/mar_2018.csv",index_col=0)
df4 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/apr_2018.csv",index_col=0)
df5 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/may_2018.csv",index_col=0)
df6 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/jun_2018.csv",index_col=0)
df7 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/jul_2018.csv",index_col=0)
df8 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/aug_2018.csv",index_col=0)
df9 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/sep_2018.csv",index_col=0)
df10 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/oct_2018.csv",index_col=0)
df11 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/nov_2018.csv",index_col=0)
df12 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/monthly-data/dec_2018.csv",index_col=0)

In [3]:
df_1 = pd.concat([df1,df2,df3,df4,df5,df6],axis=0)
df_2 = pd.concat([df7,df8,df9,df10,df11,df12],axis=0)

In [4]:
df_2

,Unnamed: 0.1,RFDE_CUST_REG_NUM,RFDE_RPT_DT,RFDE_TXN_ID,FII,SUB_ACC,BRKER,SCRIP_NAME,ISIN,TR_DATE,TR_TYPE(*),RFDE_SE_REG_NUM,RFDE_STLD_CODE,RATE,QUANTITY,VALUE (in Rs),RFDE_INSTR_TYPE,RFDE_REASON_DLAY,RFDE_RPT_TYPE,RFDE_AMDMNT_REASON
0,1.0,5,2018-07-25,64463,F548521206073,S640076734501,B617642239091,BINANI INDUSTRIES LI,INE071A01013,2018-07-24,1,23,REG_DL_STLD_01,83.6700,5000.00,4.183500e+05,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
1,2.0,5,2018-07-25,64464,F548521206073,S640076734501,B617642239091,S H KELKAR AND COMPA,INE500L01026,2018-07-24,1,23,REG_DL_STLD_01,199.9989,15000.00,2.999984e+06,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
2,3.0,5,2018-07-25,64465,F376586705576,S509891554967,B488515034552,KAJARIA CERAMICS LTD,INE217B01036,2018-07-24,4,23,REG_DL_STLD_01,430.3315,34635.00,1.490453e+07,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
3,4.0,IN/CUS/023,2018-07-02,0H00000R956M,F1160573304559,S1069289051771,B469118826307,ICICI PRUDENTIAL MF BHARAT 22 ETF,INF109KB15Y7,2018-07-02,2,99,REG_DL_STLD_04,33.8213,82039928.00,2.774697e+09,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
4,5.0,IN/CUS/023,2018-07-02,0H00000R956L,F1160573304559,S1069289051771,B469118826307,ICICI PRUDENTIAL MF BHARAT 22 ETF,INF109KB15Y7,2018-07-02,2,99,REG_DL_STLD_04,33.8213,30719913.00,1.038987e+09,REG_DL_INSTR_ME,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106129,NaN,6,2019-01-03,1587481,F684001260587,S927633912679,B769697235196,HDFC Mutual Fund,INF179K01830,2018-12-31,10,99,REG_DL_STLD_02,188.6340,51676.68,9.747979e+06,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
106130,NaN,6,2019-01-03,1587476,F684001260587,S927633912679,B769697235196,HDFC Mutual Fund,INF179K01AM7,2018-12-31,10,99,REG_DL_STLD_02,35.5110,57221.31,2.031986e+06,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
106131,NaN,6,2019-01-03,1587473,F684001260587,S927633912679,B769697235196,HDFC Mutual Fund,INF179K01AM7,2018-12-31,10,99,REG_DL_STLD_02,35.5110,166814.71,5.923757e+06,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
106132,NaN,6,2019-01-03,1587469,F684001260587,S927633912679,B769697235196,HDFC Mutual Fund,INF179K01830,2018-12-31,10,99,REG_DL_STLD_02,188.6340,44968.91,8.482665e+06,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
106133,NaN,3,2019-01-03,C00004465617,F403312356100,S559404359233,B596596249448,JUST DIAL LIMITED,INE599M01018,2018-12-27,13,23,REG_DL_STLD_01,602.1600,55.00,3.311880e+04,REG_DL_INSTR_EQ,REG_DL_DLAY_D,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00

,RFDE_CUST_REG_NUM,RFDE_RPT_DT,RFDE_TXN_ID,FII,SUB_ACC,BRKER,SCRIP_NAME,ISIN,TR_DATE,TR_TYPE(*),RFDE_SE_REG_NUM,RFDE_STLD_CODE,RATE,QUANTITY,VALUE (in Rs),RFDE_INSTR_TYPE,RFDE_REASON_DLAY,RFDE_RPT_TYPE,RFDE_AMDMNT_REASON,Unnamed: 0.1
0,9,2018-01-01,180000314,F694434372708,S476572906396,B769686235185,VAKRANGEE TEMP ISIN DM1,IN8051B01012,2018-01-01,7,99,REG_DL_STLD_04,0.0000,345739.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
1077,5,2018-01-02,61537,F513981817122,S1130374325845,B583618273855,STERLING BIOTECH LTD,INE324C01038,2018-01-01,1,23,REG_DL_STLD_01,4.2014,475000.0,1.995665e+06,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
1076,5,2018-01-02,61550,F1041965594838,S530529631149,B777227697971,ALLCARGO LOGISTICS L,INE418H01029,2018-01-01,1,23,REG_DL_STLD_01,210.9152,10000.0,2.109152e+06,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
1075,5,2018-01-02,61535,F1013807183429,S909067658907,B536958863812,ADF FOODS LTD 40 A,INE982B01019,2018-01-01,1,23,REG_DL_STLD_01,314.9445,64000.0,2.015645e+07,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
1074,5,2018-01-02,61549,F1106095156084,S687435461202,B737160285974,CREST VENTURES LIMIT,INE559D01011,2018-01-01,4,23,REG_DL_STLD_01,295.0000,6411.0,1.891245e+06,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128860,IN/CUS/024,2018-07-03,413290,F1124791047670,S953344843325,B469117826306,HIKAL LIMITED FV 2,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,10450.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,128861.0
124280,6,2018-07-02,1560672,F1051193966596,S421156293192,B469117826306,Hikal Ltd,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,248490.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,124281.0
127588,3,2018-07-02,R00000217655,F669183610649,S868082909740,B469117826306,HIKAL LIMITED TRADING AND LISTING,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,19856.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,127589.0
128842,IN/CUS/024,2018-07-02,207201801,F1094896472166,S1063130094747,B469117826306,BHARAT 22 ETF,INF109KB15Y7,2018-06-30,2,99,REG_DL_STLD_04,33.8213,4810696.0,1.627040e+08,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,128843.0
127909,3,2018-07-02,R00000217651,F1033832325650,S415568015013,B469117826306,HIKAL LIMITED TRADING AND LISTING,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,998.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,127910.0

In [6]:
#del df_1['Unnamed: 0.1']

In [13]:
df_1['TR_DATE'] = df_1['TR_DATE'].astype('datetime64[D]')
df_1.sort_values('TR_DATE',inplace=True)
df_1['TR_DATE']
df_1= df_1.reset_index()
del df_1['index']
df_1

,RFDE_CUST_REG_NUM,RFDE_RPT_DT,RFDE_TXN_ID,FII,SUB_ACC,BRKER,SCRIP_NAME,ISIN,TR_DATE,TR_TYPE(*),RFDE_SE_REG_NUM,RFDE_STLD_CODE,RATE,QUANTITY,VALUE (in Rs),RFDE_INSTR_TYPE,RFDE_REASON_DLAY,RFDE_RPT_TYPE,RFDE_AMDMNT_REASON,Unnamed: 0.1
0,9,2018-01-01,180000314,F694434372708,S476572906396,B769686235185,VAKRANGEE TEMP ISIN DM1,IN8051B01012,2018-01-01,7,99,REG_DL_STLD_04,0.0000,345739.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
1,9,2018-01-01,180000285,F1155223174449,S624933553795,B769686235185,VAKRANGEE TEMP ISIN DM1,IN8051B01012,2018-01-01,7,99,REG_DL_STLD_04,0.0000,8608.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
2,9,2018-01-01,180000857,F761086797404,S479936724329,B1152917331511,UPL LIMITED DM2.,INE628A01036,2018-01-01,1,1,REG_DL_STLD_01,761.1521,5596.0,4.259407e+06,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
3,9,2018-01-01,180000493,F937768621596,S564791744454,B1152917331511,LUPIN LIMITED DM2,INE326A01037,2018-01-01,4,23,REG_DL_STLD_01,884.8602,546.0,4.831337e+05,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
4,9,2018-01-01,180000156,F548406695811,S444263977697,B769686235185,VAKRANGEE TEMP ISIN DM1,IN8051B01012,2018-01-01,7,99,REG_DL_STLD_04,0.0000,217285.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726567,3,2018-07-02,R00000217656,F645962415883,S485231599310,B469117826306,HIKAL LIMITED TRADING AND LISTING,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,13721.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,126895.0
726568,3,2018-07-02,R00000217652,F928007698569,S490440091594,B469117826306,HIKAL LIMITED TRADING AND LISTING,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,17328.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,128263.0
726569,IN/CUS/024,2018-07-02,207201801,F1094896472166,S1063130094747,B469117826306,BHARAT 22 ETF,INF109KB15Y7,2018-06-30,2,99,REG_DL_STLD_04,33.8213,4810696.0,1.627040e+08,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,128843.0
726570,IN/CUS/024,2018-07-02,207201802,F1094896472166,S1063130094747,B469117826306,BHARAT 22 ETF,INF109KB15Y7,2018-06-30,2,99,REG_DL_STLD_04,33.8213,6041754.0,2.043400e+08,REG_DL_INSTR_MD,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,128857.0
726571,3,2018-07-02,R00000217651,F1033832325650,S415568015013,B469117826306,HIKAL LIMITED TRADING AND LISTING,IN8475B01021,2018-06-30,7,99,REG_DL_STLD_04,0.0000,998.0,0.000000e+00,REG_DL_INSTR_EU,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00,127910.0

In [14]:
df_2['TR_DATE'] = df_2['TR_DATE'].astype('datetime64[D]')
df_2.sort_values('TR_DATE',inplace=True)
df_2['TR_DATE']
df_2= df_2.reset_index()
del df_2['index']
df_2['TR_DATE']

0        2018-07-02
1        2018-07-02
2        2018-07-02
3        2018-07-02
4        2018-07-02
            ...
680334   2018-12-31
680335   2018-12-31
680336   2018-12-31
680337   2018-12-31
680338   2018-12-31
Name: TR_DATE, Length: 680339, dtype: datetime64[ns]

In [15]:

#del df_1['BSE_High']
#del df_1['BSE_Low']
#del df_1['BSE_Close']
#del df_1['BSE_Open']
#del df_2['BSE_High']
#del df_2['BSE_Low']
#del df_2['BSE_Close']
#del df_2['BSE_Open']


df_1.to_csv("/Users/garg/Desktop/thesis/data/2018/jan_to_jun_2018.csv")
df_2.to_csv("/Users/garg/Desktop/thesis/data/2018/jul_to_dec_2018.csv")

In [16]:
import pandas as pd 
df1 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/jul_to_dec_2018.csv",index_col=0)
df1

,Unnamed: 0.1,RFDE_CUST_REG_NUM,RFDE_RPT_DT,RFDE_TXN_ID,FII,SUB_ACC,BRKER,SCRIP_NAME,ISIN,TR_DATE,TR_TYPE(*),RFDE_SE_REG_NUM,RFDE_STLD_CODE,RATE,QUANTITY,VALUE (in Rs),RFDE_INSTR_TYPE,RFDE_REASON_DLAY,RFDE_RPT_TYPE,RFDE_AMDMNT_REASON
0,3802.0,4,2018-07-03,11279431,F577059403378,S921308190267,B1005050980269,ITC LTD,INE154A01025,2018-07-02,1,23,REG_DL_STLD_01,263.6086,12021.0,3168838.98,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
1,3426.0,4,2018-07-03,11279497,F577059403378,S921308190267,B1005050980269,REL NIPPON LIFE ASSET MGMT LTD (X REL CA,INE298J01013,2018-07-02,4,23,REG_DL_STLD_01,230.6573,212.0,48899.35,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
2,3425.0,4,2018-07-03,11277905,F485992171102,S520281411971,B986604236764,RAMAKRISHNA FORGINGS LTD,INE399G01015,2018-07-02,1,1,REG_DL_STLD_01,653.8385,26.0,16999.80,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
3,3424.0,4,2018-07-03,11278377,F785263456915,S831787229138,B437325321325,BATA INDIA INR 5,INE176A01028,2018-07-02,1,23,REG_DL_STLD_01,845.7830,1177.0,995486.59,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
4,3423.0,4,2018-07-03,11279422,F415840290653,S1199718379380,B1005050980269,HEXAWARE TECHNOLOGIES LTD. (INR 2),INE093A01033,2018-07-02,4,23,REG_DL_STLD_01,460.4083,744.0,342543.78,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680334,NaN,9,2019-01-01,190000210,F1185074494837,S676514052929,B1006358103345,HINDUSTAN UNILEVER LTD DM1,INE030A01027,2018-12-31,1,23,REG_DL_STLD_01,1833.3838,348.0,638017.56,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
680335,NaN,9,2019-01-01,190000460,F721328788622,S1015717112918,B1006358103345,LIC HSG FINANCE LTD DM2,INE115A01026,2018-12-31,1,23,REG_DL_STLD_01,488.8844,38373.0,18759961.08,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
680336,NaN,9,2019-01-01,190000415,F932733894707,S1032373437201,B1182334610875,L AND T FINANCE HOLD LTD DM,INE498L01015,2018-12-31,1,23,REG_DL_STLD_01,152.9999,5281.0,807992.47,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
680337,NaN,9,2019-01-01,190000315,F664767817726,S814376333069,B1088934408096,CONTAINER CORPORATION DM5,INE111A01025,2018-12-31,1,23,REG_DL_STLD_01,688.0408,65.0,44722.65,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00
680338,NaN,14,2019-01-01,9818817,F460768536607,S752715380145,B490907260187,RELIANCE INDUSTRIES LTD EQ FV10,INE002A01018,2018-12-31,4,23,REG_DL_STLD_01,1122.4655,1469.0,1648901.82,REG_DL_INSTR_EQ,REG_DL_DLAY_P,DL_RPT_TYPE_N,DL_AMDMNT_DEL_00

In [17]:
df1.dtypes

Unnamed: 0.1          float64
RFDE_CUST_REG_NUM      object
RFDE_RPT_DT            object
RFDE_TXN_ID            object
FII                    object
SUB_ACC                object
BRKER                  object
SCRIP_NAME             object
ISIN                   object
TR_DATE                object
TR_TYPE(*)              int64
RFDE_SE_REG_NUM         int64
RFDE_STLD_CODE         object
RATE                  float64
QUANTITY              float64
VALUE (in Rs)         float64
RFDE_INSTR_TYPE        object
RFDE_REASON_DLAY       object
RFDE_RPT_TYPE          object
RFDE_AMDMNT_REASON     object
dtype: object

In [18]:
df2 = pd.read_csv("/Users/garg/Desktop/thesis/data/2018/jan_to_jun_2018.csv",index_col = 0)
df2.dtypes

RFDE_CUST_REG_NUM      object
RFDE_RPT_DT            object
RFDE_TXN_ID            object
FII                    object
SUB_ACC                object
BRKER                  object
SCRIP_NAME             object
ISIN                   object
TR_DATE                object
TR_TYPE(*)              int64
RFDE_SE_REG_NUM         int64
RFDE_STLD_CODE         object
RATE                  float64
QUANTITY              float64
VALUE (in Rs)         float64
RFDE_INSTR_TYPE        object
RFDE_REASON_DLAY       object
RFDE_RPT_TYPE          object
RFDE_AMDMNT_REASON     object
Unnamed: 0.1          float64
dtype: object

In [5]:
df2.dtypes

RFDE_CUST_REG_NUM      object
RFDE_RPT_DT            object
RFDE_TXN_ID            object
FII                    object
SUB_ACC                object
BRKER                  object
SCRIP_NAME             object
ISIN                   object
TR_DATE                object
TR_TYPE(*)              int64
RFDE_SE_REG_NUM         int64
RFDE_STLD_CODE         object
RATE                  float64
QUANTITY              float64
VALUE (in Rs)         float64
RFDE_INSTR_TYPE        object
RFDE_REASON_DLAY       object
RFDE_RPT_TYPE          object
RFDE_AMDMNT_REASON     object
foreign-exchange      float64
Year-Month             object
Inflation-Rate        float64
FDI-Inward            float64
Year                    int64
FDI-Growth-Rate       float64
GDP-Growth-Rate       float64
IIP                   float64
unemployment-rate     float64
BSE_Close             float64
twitter-sentiment     float64
Real-GDP              float64
dtype: object

In [6]:
df = pd.concat([df1,df2],axis=0)

,RFDE_CUST_REG_NUM,RFDE_RPT_DT,RFDE_TXN_ID,FII,SUB_ACC,BRKER,SCRIP_NAME,ISIN,TR_DATE,TR_TYPE(*),...,Inflation-Rate,FDI-Inward,Year,FDI-Growth-Rate,GDP-Growth-Rate,IIP,unemployment-rate,BSE_Close,twitter-sentiment,Real-GDP
0,IN/CUS/017,2019-07-08,160974,F491029387846,S329538999481,B1089029408191,BSE LIMITED,INE118H01025,2019-07-05,1,...,5.980066,60317.44,2019,0.02,5.759931,115.2685,5.355,39513.39,0.047490,5.2
1,IN/CUS/017,2019-07-11,161102,F491029387846,S329538999481,B1089029408191,BSE LIMITED,INE118H01025,2019-07-10,1,...,5.980066,60317.44,2019,0.02,5.759931,115.2685,5.355,38557.04,0.052325,5.2
2,4,2019-07-29,12231499,F899434863545,S890428512304,B497892661533,AARTI INDUSTRIES LTD,INE769A01020,2019-07-26,4,...,5.980066,60317.44,2019,0.02,5.759931,115.2685,5.355,37882.79,0.067698,5.2
3,5,2019-07-25,68502,F386425501145,S912211946179,B912591732074,CAN FIN HOMES LTD FV,INE477A01020,2019-07-24,4,...,5.980066,60317.44,2019,0.02,5.759931,115.2685,5.355,37847.65,0.033241,5.2
4,5,2019-07-25,68503,F1116618140758,S509991555067,B1086289524230,EICHER MOTORS LTD,INE066A01013,2019-07-24,1,...,5.980066,60317.44,2019,0.02,5.759931,115.2685,5.355,37847.65,0.033241,5.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105647,9,2020-01-02,200000341,F767816923125,S416379331782,B964220486331,CROMPTON GRE CON ELE LTD DM,INE299U01018,2019-12-31,1,...,9.634551,60317.44,2019,0.02,5.759931,115.2685,5.355,41253.74,-3.000000,4.4
105648,9,2020-01-02,200000337,F661910913353,S979873090746,B517456635167,RELAXO FOOTWEAR LTD DM1,INE131B01039,2019-12-31,1,...,9.634551,60317.44,2019,0.02,5.759931,115.2685,5.355,41253.74,-3.000000,4.4
105649,9,2020-01-02,200000352,F494262567965,S647614687136,B964220486331,CROMPTON GRE CON ELE LTD DM,INE299U01018,2019-12-31,1,...,9.634551,60317.44,2019,0.02,5.759931,115.2685,5.355,41253.74,-3.000000,4.4
105650,IN/CUS/017,2020-01-02,167491,F576757490024,S1162468723887,B769797235296,KOTAK MAHINDRA MUTUAL FUND STANDARD MULT,INF174K01LS2,2019-12-30,8,...,9.634551,60317.44,2019,0.02,5.759931,115.2685,5.355,41558.00,-3.000000,4.4
105651,9,2020-01-03,200000653,F666875257561,S657841778756,B583729273966,HDFC LTD DM2,INE001A01036,2019-12-31,1,...,9.634551,60317.44,2019,0.02,5.759931,115.2685,5.355,41253.74,-3.000000,4.4

In [8]:
df['TR_DATE'] = df['TR_DATE'].astype('datetime64[D]')

0        2019-07-05
1        2019-07-10
2        2019-07-26
3        2019-07-24
4        2019-07-24
            ...
105647   2019-12-31
105648   2019-12-31
105649   2019-12-31
105650   2019-12-30
105651   2019-12-31
Name: TR_DATE, Length: 663349, dtype: datetime64[ns]

In [10]:
df = df.sort_values('TR_DATE')

In [11]:
df['TR_DATE'].unique()

array(['2019-07-01T00:00:00.000000000', '2019-07-02T00:00:00.000000000',
       '2019-07-03T00:00:00.000000000', '2019-07-04T00:00:00.000000000',
       '2019-07-05T00:00:00.000000000', '2019-07-08T00:00:00.000000000',
       '2019-07-09T00:00:00.000000000', '2019-07-10T00:00:00.000000000',
       '2019-07-11T00:00:00.000000000', '2019-07-12T00:00:00.000000000',
       '2019-07-15T00:00:00.000000000', '2019-07-16T00:00:00.000000000',
       '2019-07-17T00:00:00.000000000', '2019-07-18T00:00:00.000000000',
       '2019-07-19T00:00:00.000000000', '2019-07-22T00:00:00.000000000',
       '2019-07-23T00:00:00.000000000', '2019-07-24T00:00:00.000000000',
       '2019-07-25T00:00:00.000000000', '2019-07-26T00:00:00.000000000',
       '2019-07-29T00:00:00.000000000', '2019-07-30T00:00:00.000000000',
       '2019-07-31T00:00:00.000000000', '2019-08-01T00:00:00.000000000',
       '2019-08-02T00:00:00.000000000', '2019-08-03T00:00:00.000000000',
       '2019-08-05T00:00:00.000000000', '2019-08-06T00:00:00.000000000',
       '2019-08-07T00:00:00.000000000', '2019-08-08T00:00:00.000000000',
       '2019-08-09T00:00:00.000000000', '2019-08-13T00:00:00.000000000',
       '2019-08-14T00:00:00.000000000', '2019-08-16T00:00:00.000000000',
       '2019-08-19T00:00:00.000000000', '2019-08-20T00:00:00.000000000',
       '2019-08-21T00:00:00.000000000', '2019-08-22T00:00:00.000000000',
       '2019-08-23T00:00:00.000000000', '2019-08-26T00:00:00.000000000',
       '2019-08-27T00:00:00.000000000', '2019-08-28T00:00:00.000000000',
       '2019-08-29T00:00:00.000000000', '2019-08-30T00:00:00.000000000',
       '2019-09-03T00:00:00.000000000', '2019-09-04T00:00:00.000000000',
       '2019-09-05T00:00:00.000000000', '2019-09-06T00:00:00.000000000',
       '2019-09-07T00:00:00.000000000', '2019-09-09T00:00:00.000000000',
       '2019-09-11T00:00:00.000000000', '2019-09-12T00:00:00.000000000',
       '2019-09-13T00:00:00.000000000', '2019-09-16T00:00:00.000000000',
       '2019-09-17T00:00:00.000000000', '2019-09-18T00:00:00.000000000',
       '2019-09-19T00:00:00.000000000', '2019-09-20T00:00:00.000000000',
       '2019-09-21T00:00:00.000000000', '2019-09-23T00:00:00.000000000',
       '2019-09-24T00:00:00.000000000', '2019-09-25T00:00:00.000000000',
       '2019-09-26T00:00:00.000000000', '2019-09-27T00:00:00.000000000',
       '2019-09-30T00:00:00.000000000', '2019-10-01T00:00:00.000000000',
       '2019-10-03T00:00:00.000000000', '2019-10-04T00:00:00.000000000',
       '2019-10-07T00:00:00.000000000', '2019-10-09T00:00:00.000000000',
       '2019-10-10T00:00:00.000000000', '2019-10-11T00:00:00.000000000',
       '2019-10-14T00:00:00.000000000', '2019-10-15T00:00:00.000000000',
       '2019-10-16T00:00:00.000000000', '2019-10-17T00:00:00.000000000',
       '2019-10-18T00:00:00.000000000', '2019-10-19T00:00:00.000000000',
       '2019-10-22T00:00:00.000000000', '2019-10-23T00:00:00.000000000',
       '2019-10-24T00:00:00.000000000', '2019-10-25T00:00:00.000000000',
       '2019-10-27T00:00:00.000000000', '2019-10-29T00:00:00.000000000',
       '2019-10-30T00:00:00.000000000', '2019-10-31T00:00:00.000000000',
       '2019-11-01T00:00:00.000000000', '2019-11-04T00:00:00.000000000',
       '2019-11-05T00:00:00.000000000', '2019-11-06T00:00:00.000000000',
       '2019-11-07T00:00:00.000000000', '2019-11-08T00:00:00.000000000',
       '2019-11-11T00:00:00.000000000', '2019-11-13T00:00:00.000000000',
       '2019-11-14T00:00:00.000000000', '2019-11-15T00:00:00.000000000',
       '2019-11-18T00:00:00.000000000', '2019-11-19T00:00:00.000000000',
       '2019-11-20T00:00:00.000000000', '2019-11-21T00:00:00.000000000',
       '2019-11-22T00:00:00.000000000', '2019-11-25T00:00:00.000000000',
       '2019-11-26T00:00:00.000000000', '2019-11-27T00:00:00.000000000',
       '2019-11-28T00:00:00.000000000', '2019-11-29T00:00:00.000000000',
       '2019-12-02T00:00:00.000000000', '2019-12-03T00:00:00.000000000',
       '2019-12-04T00:00:00.000000000', '2019-12-05T00:00:00.000000000',
       '2019-12-06T00:00:00.000000000', '2019-12-07T00:00:00.000000000',
       '2019-12-09T00:00:00.000000000', '2019-12-10T00:00:00.000000000',
       '2019-12-11T00:00:00.000000000', '2019-12-12T00:00:00.000000000',
       '2019-12-13T00:00:00.000000000', '2019-12-16T00:00:00.000000000',
       '2019-12-17T00:00:00.000000000', '2019-12-18T00:00:00.000000000',
       '2019-12-19T00:00:00.000000000', '2019-12-20T00:00:00.000000000',
       '2019-12-21T00:00:00.000000000', '2019-12-23T00:00:00.000000000',
       '2019-12-24T00:00:00.000000000', '2019-12-26T00:00:00.000000000',
       '2019-12-27T00:00:00.000000000', '2019-12-30T00:00:00.000000000',
       '2019-12-31T00:00:00.000000000'], dtype='datetime64[ns]')

In [13]:
df.to_csv("/Users/garg/Desktop/thesis/data/2019/jul_to_dec_2019.csv")